#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks-per-node=32
#SBATCH --partition=tc

export SCM_TMPDIR=/scratch/${SLURM_JOBID}
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"

module load ams/2022.103
module list


$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out


Task SinglePoint


System
  Atoms
C      -0.03239656       0.00000000       1.11299016
F       3.90365218       0.35426096       0.49491288
C      -0.07121503      -1.18953976       0.18396896
C       0.02207559      -0.73864883      -1.08026139
C       0.02207559       0.73864883      -1.08026139
C      -0.07121503       1.18953976       0.18396896
H      -0.09785701      -2.21661345       0.52846779
H       0.09099444      -1.34824429      -1.97642645
H       0.09099444       1.34824429      -1.97642645
H      -0.09785701       2.21661345       0.52846779
H       0.94154358       0.00000000       1.63762041
F      -1.01915507       0.00000000       2.10529389
  End
Charge -1.0
End


Engine ADF
  
  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY AUTO
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA OLYP
  END
  
  NumericalQuality VERYGOOD
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.log

rm -r ams.results
